// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5x-WSNtU0hCs12pMoMaZV8YQwoQJdBAQ',
    appId: '1:1017987650151:web:6b3eb96f9a01ae0accbac2',
    messagingSenderId: '1017987650151',
    projectId: 'ygobinder-e31e1',
    authDomain: 'ygobinder-e31e1.firebaseapp.com',
    storageBucket: 'ygobinder-e31e1.firebasestorage.app',
    measurementId: 'G-7LRBRNTQNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkyXlJbov4KHCC3-m8gQHaGWE8oDOSy50',
    appId: '1:1017987650151:android:7c96bcda738e417dccbac2',
    messagingSenderId: '1017987650151',
    projectId: 'ygobinder-e31e1',
    storageBucket: 'ygobinder-e31e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtiW3XXrtQiayxLbE-AH1fqYNd82G2Dk',
    appId: '1:1017987650151:ios:627a154c06b5ffc6ccbac2',
    messagingSenderId: '1017987650151',
    projectId: 'ygobinder-e31e1',
    storageBucket: 'ygobinder-e31e1.firebasestorage.app',
    iosBundleId: 'com.tsuna2001.ygobinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtiW3XXrtQiayxLbE-AH1fqYNd82G2Dk',
    appId: '1:1017987650151:ios:627a154c06b5ffc6ccbac2',
    messagingSenderId: '1017987650151',
    projectId: 'ygobinder-e31e1',
    storageBucket: 'ygobinder-e31e1.firebasestorage.app',
    iosBundleId: 'com.tsuna2001.ygobinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5x-WSNtU0hCs12pMoMaZV8YQwoQJdBAQ',
    appId: '1:1017987650151:web:593b0522db8d2254ccbac2',
    messagingSenderId: '1017987650151',
    projectId: 'ygobinder-e31e1',
    authDomain: 'ygobinder-e31e1.firebaseapp.com',
    storageBucket: 'ygobinder-e31e1.firebasestorage.app',
    measurementId: 'G-N6PD8F7SSL',
  );
}
